### ISSUE TITLE
Termina el ejercicio!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/f-m3-evaluacion-intermedia-ArianeJDB#1]
Buen trabajo @ArianeJDB !

Algunas pistas para acabarlo:

- [x] Como sugerencia general, comprueba continuamente tu aplicación en Chrome y el terminal dónde arrancas la app con `npm start`. Si algo falla, hay que arreglarlo antes de continuar.
- [x] Termina de añadir los componentes finales: recuerda que **PokeList** suele contener la lista de elementos y **Pokemon** tendrá solo la tarjeta
- [x] Termina de añadir los elementos finales de la tarjeta de cada Pokemon: un div o article que la englobe
- [x] Termina de añadir los elementos finales de la tarjeta de cada Pokemon: los tipos tienen que ser una lista, no pueden ser h3 sueltos, recuerda que son elementos relacionados. Un OL o UL es lo suyo.
- [x] Utiliza el nombre del Pokemon para el Alt de la imagen
- [x] Mueve el `li` del componente 'PokeList' fuera del div. Las hijas inmediatas de un UL/OL solo pueden ser LI
- [x] Añade un título a la página (Mi lista de Pokemons)
- [x] Usa el `id` de cada pokemon para el  `key` de react cuando mapeas y creas un listado de componentes
- [x] Añade estilos (un archivo sass o css por componente)
- [x] Usa propTypes para comprobar el tipo de dato de las props
- [x] Revisa los metadatos en index.html (lang, title...)
- [x] Limpia e indenta el código
- [x] Publica en Github Pages

Cuando tengas esto puedes:

1. Mover el array de pokemons a otro archivo e importarlo en App.
2. Inicializar el estado de App con el array de pokemons y utilizar este en lugar de la constante `pokemon`.
3. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
4. Pasar este dato al componente Pokemon por props
5. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón

**Comment by ArianeJDB** [comment]
Fixed all the issues except the extras which I will do later. Thank you

**Comment by oneeyedman** [comment]
Buenas, @ArianeJDB: te he desmarcado las cosas que no están hechas. Mañana nos sentamos y las vemos.

**Comment by oneeyedman** [comment]
Buenas, @ArianeJDB, lo damos por cerrado!
